#!/usr/bin/env node
/**
 * Write the service worker, with a precache manifest generated from the real
 * build output.
 *
 * This runs after `astro build` because the asset filenames are fingerprinted
 * and only exist once the build has run. A hand-written list would be wrong the
 * first time a stylesheet changed, and the failure mode — a lesson that is
 * offline-ready except for its fonts — is exactly the one that ruins a Tuesday.
 *
 * What gets precached (spec §13): the shell, the fonts, and every lesson deck
 * and guide. The whole site is small enough that precaching all of it is simpler
 * and more reliable than trying to be clever about "the current unit".
 */
import { readFileSync, writeFileSync, readdirSync, statSync } from 'node:fs'
import { createHash } from 'node:crypto'
import path from 'node:path'
import { ROOT } from './lib/curriculum.mjs'

const DIST = path.join(ROOT, 'dist')
const BASE = readBase()

const walk = (dir) =>
  readdirSync(dir, { withFileTypes: true }).flatMap((d) => {
    const abs = path.join(dir, d.name)
    return d.isDirectory() ? walk(abs) : [abs]
  })

// Everything except the things that would be silly to cache.
const SKIP = /(?:^|\/)(?:sitemap[^/]*\.xml|robots\.txt|sw\.js|placeholders\.json)$/

const files = walk(DIST)
  .map((abs) => '/' + path.relative(DIST, abs).split(path.sep).join('/'))
  .filter((url) => !SKIP.test(url))
  .sort()

// index.html files are addressed by their directory, which is how the browser
// will actually request them.
const urls = [
  ...new Set(files.map((u) => (u.endsWith('/index.html') ? u.slice(0, -'index.html'.length) : u))),
]

const withBase = urls.map((u) => (BASE + u.replace(/^\//, '')).replace(/\/{2,}/g, '/'))

const bytes = files.reduce((n, u) => n + statSync(path.join(DIST, u)).size, 0)

// The cache name carries a hash of the manifest, so a deploy that changes any
// asset rolls the cache and the old one is deleted on activate.
const version = createHash('sha256').update(withBase.join('\n')).digest('hex').slice(0, 12)

const sw = `/* Generated by scripts/build-sw.mjs. Do not edit — edit that script.
 *
 * Offline is a hard requirement (spec §1): home internet failing must not
 * cancel a lesson. Everything is precached on install, so a deck opened once on
 * the sofa is a deck that works at the kitchen table with the router unplugged.
 *
 * Nothing here talks to any third party, and nothing is ever reported anywhere.
 */
const CACHE = 'computers-${version}'
const BASE = ${JSON.stringify(BASE)}
const PRECACHE = ${JSON.stringify(withBase, null, 2)}

self.addEventListener('install', (event) => {
  event.waitUntil(
    caches
      .open(CACHE)
      // addAll() is all-or-nothing; one 404 would leave the whole lesson
      // uncached, so each request is allowed to fail on its own.
      .then((cache) =>
        Promise.all(
          PRECACHE.map((url) => cache.add(url).catch(() => {}))
        )
      )
      .then(() => self.skipWaiting())
  )
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim())
  )
})

self.addEventListener('fetch', (event) => {
  const request = event.request
  if (request.method !== 'GET') return

  const url = new URL(request.url)
  if (url.origin !== self.location.origin) return
  if (!url.pathname.startsWith(BASE)) return

  // Cache-first. The content is static and a rebuild rolls the whole cache, so
  // there is no staleness to reason about — and cache-first is what makes this
  // fast on a Pi 400 as well as what makes it work on a dead connection.
  event.respondWith(
    caches.match(request, { ignoreSearch: true }).then((hit) => {
      if (hit) return hit
      return fetch(request)
        .then((response) => {
          if (response.ok && response.type === 'basic') {
            const copy = response.clone()
            caches.open(CACHE).then((cache) => cache.put(request, copy))
          }
          return response
        })
        .catch(() =>
          // Offline and never seen: fall back to the deck's own page shell if we
          // have it, otherwise let it fail honestly.
          caches.match(BASE) ?? Response.error()
        )
    })
  )
})

// The page asks whether it is safe to unplug the router.
self.addEventListener('message', (event) => {
  if (event.data === 'cache-status') {
    caches.open(CACHE).then((cache) =>
      cache.keys().then((keys) => {
        event.source?.postMessage({ cached: keys.length, total: PRECACHE.length })
      })
    )
  }
})
`

writeFileSync(path.join(DIST, 'sw.js'), sw)

console.log(
  `sw: precaching ${withBase.length} URLs (${(bytes / 1024).toFixed(0)} KB) as computers-${version}`
)

function readBase() {
  const config = readFileSync(path.join(ROOT, 'astro.config.mjs'), 'utf8')
  const base = config.match(/const BASE\s*=\s*'([^']+)'/)?.[1]
  if (!base) throw new Error('Could not read BASE from astro.config.mjs')
  return base
}
